
* Skills

** Programming
:properties:
:CV_ENV:   cvskill
:RATING:   5
:end:
 Scala, JavaScript/Typescript, Golang, C#, Java, PHP, AS3, Unity3D

** Frontend
:properties:
:CV_ENV:   cvskill
:RATING:   4
:end:
HTML/CSS, React, GraphQL, Apollo UI, Redux, Webpack, Babel, SystemJS

** Databases
:properties:
:CV_ENV:   cvskill
:RATING:   3
:end:
PostgresSql, MySQL, MsSQL, MongoDB

** Backend
:properties:
:CV_ENV:   cvskill
:RATING:   4
:end:

NodeJS, Thrift, Play Framework, Finagle, Express, Apollo Federation

** Devops
:properties:
:CV_ENV:   cvskill
:RATING:   4
:ID:       e9ec5a93-463b-4238-ad15-3f6efcbf1a89
:end:
Kubernetes, Terraform, AWS, Nginx, ArgoCD, Helm, Open Tracing, Jenkins, Drone.io

** Tools
:properties:
:CV_ENV:   cvskill
:RATING:   4
:end:
Git, Subversion, Mercurial


* Experience
** Principal Software Engineer
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2015-09-21>
:TO:       <2021-12-07>
:LOCATION: NYC, NY
:EMPLOYER: Fevo
:ID:       ad3f322a-a7f2-43d7-8919-ef9c0e21e111
:END:
Development lead for many critical projects and innovations. Responsible for team technical standards, development processes, code quality, and high-level design choices.
Spearheaded improvements such as:
- Better practices in dependency management with versioning and central artifact repositories.
- Cattle not pets by leveraging Kubernetes and auto scaling groups rather then manually cared for ec2 instances.
- Infrastructure as code by creating terraform modules for aws provisioning and Kubernetes manifests (Helm with Argo) for application provisioning.
- De-stressed production deployments by adding Github checks, automating deployments, adding self serviced environments, and providing blue/green production deploys.
- Containerized existing services and build processes, and provided a template for new service development.
- Moved configuration to environment variables and appropriate secret stores, rather then version control.
- Enabled easy, and some automatic, scaling of services and infrastructure.
- Usage of component driven UI development including react.
- Predictable UI state management with redux and Apollo.
- Better frontend typesaftey with typescript and graphql.

*** Patents
**** Systems And Methods Of Group Electronic Commerce And Distribution Of Items
:PROPERTIES:
:CV_ENV:   cvachievement
:ICON: Gavel
:END:
Co-Author, US 20200394705 A1, published 2020-12-17

*** Projects
**** Authentication Authorization and Administration
:PROPERTIES:
:CV_ENV:   cvproject
:ROLE:     Architect, Staff Principal Engineer
:END:
Restructuring of many of Fevo's core components to support open standards for user identity and access management.
- Built a multi-tenant fine grained authorization system, which was driven from business people defining relationships and feature sets in salesforce.
- Moved authentication out of many frontend applications and instead leveraged OIDC with single sign on.
- Moved authorization out of ad hoc patterns and into Oath2 claims and authorization services / policies.
=Keycloak= =Java= =Golang= =Scala=

**** Collective Commerce
:PROPERTIES:
:CV_ENV:   cvproject
:ROLE:     Architect, Prinicpal Software Engineer
:END:
Prototyped and built from the ground up the next phase of Fevo's ecommerce flows. A universal shopping cart supporting flexible types of offers and UIs, large social groups, with an evolutionary architecture.
- Platform capable of managing inventory plugged in from several different integration services.
- Flexible models and user interfaces to support listing and purchases of many types of offer, including event tickets, hotel rooms, merch, and various bundles.
- Unified graphql API to support all the customizable frontend flows.
- Supported large scale flash sales and promotions by handling 40k sessions per minute.
=Scala= =GraphQL= =React= =Play framework= =Node= =Webpack= =Typescript=

**** Ticketing Integrations
:PROPERTIES:
:CV_ENV:   cvproject
:ICON: Ticket
:ROLE:     Individual Contributor, Senior Software Engineer
:END:
Integrations to support using inventory from primary ticket holders such as TicketMaster and Tickets.com.
- Extended and created services to support both Fevo's inventory management and integration with other vendors.

=Scala= =Finagle= =Thrift=

**** Client Content Management System
:PROPERTIES:
:CV_ENV:   cvproject
:ROLE:     Individual Contributor, Senior Software Engineer
:END:
Self service platform for Fevo Clients
- Built initial version of the CMS platform used by our clients.
- Built initial backend services, UI architecture and UI build systems.
- Provided real time analytics and report generation on sales, users and groups
- Gave clients complete control over creating, branding, editing, and publishing their events.
=Typescript= =React= =Redux= =Scala= =Finagle= =Playframework= =webpack=

**** Distributed Commerce
:PROPERTIES:
:CV_ENV:   cvproject
:LINK: https://www.fevo.com/resources/sdk-documentation
:ICON:     Link
:ROLE:     Individual Contributor, Software Engineer
:END:
Gave clients a custom branded way for users to purchase tickets to an event, grow a group organically via share links, pay separately, but be sat together. Designed to be frictionless while still providing visualizations for your groups growth and progress towards rewards.
- Designed and implementation of a new platform capable of being hosted by fevo and/or dropped into a clients site via a few lines of code.
- Built initial Fevo UI buy flows and UI/frontend build pipeline.
- Built supporting backend services related to users accounts, authentication, and group management.

=ES6= =Scala= =Play Framework= =Handlebars= =SystemJS= =Babel= =Java= =Dropwizard=

** Independent Developer
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2014-08-01>
:TO:       <2015-08-21>
:LOCATION: Rochester, NY
:EMPLOYER:
:END:
I left the work force temporarily to give myself the opportunity to create my own games and products.


*** Statements
:PROPERTIES:
:CV_ENV:   cvproject
:ROLE:     Creator
:LINK:     http://thrownforaloop.com/pages/statements/
:ICON:     Link
:END:

Tools to help financial advisers/brokers generate and send email statements automatically.
- Used the data sets made from trading resellers such as interactive brokers or betterment.

=Play Framework= =React= =Websockets= =BootstrapJS=

*** It Rains Fish
:PROPERTIES:
:CV_ENV:   cvproject
:ROLE:     Creator
:END:
A turn based puzzle strategy game. Players each control a field of colorful pieces, and battle each other by arranging patterns in the colors. Good puzzling is rewarded with power on the battle field.
- Shared JavaScript client and server code base.
- Online multi-player utilizing sockets.

=ES6= =NodeJS= =Socket.IO= =Express= =Browserify=

** Senior Software Engineer
:PROPERTIES:
:CV_ENV:   cventry
:FROM:     <2009-07-01>
:TO:       <2014-09-01>
:LOCATION: Rochester, NY
:EMPLOYER: Second Avenue Leanring
:END:
Development lead for multidisciplinary teams (programmers, artists, education professionals, business and subject matter experts) responsible for designing and producing serious games, educational interactives, virtual labs, and LMS software for projects awarded NSF and Department of Education grants, and projects for publishing clients including Houghton Mifflin Harcourt, W.W. Norton & Company, Pierson, and McGraw Hill.
- Championed scrum and continuous integration, by leading the team in scrum meetings and artifact production; by creating a CI server which automated builds, tests, and deployment for staging/sprint deliverables; eliminating job roles, shortening time between releases, and increasing transparency.
- Collaborated to produce game design documents, manuscripts and story boards.
- Provided support to sales team including scoping, pricing, and proposals.
- Communicated with clients for presenting deliverables, reviewing feedback, and generating requirements.

*** Projects

**** Martha Madison
:Properties:
:CV_ENV:   cvproject
:ICON: Link
:LINK: https://secondavenuelearning.com/martha-madison/
:ROLE:     Lead Developer
:END:

A series of 4 real-time 3D, collaborative, 3D puzzle platformer in games. Levels that correlate to learning objects, level editors where students create their own levels, and dashboards where teachers parents and admins track progress.
- Designed and developed game concepts and levels.
- On-boarded junior developers, designed tools, and created workflows for artists and developers.
- Developed DB schema, JSON API, and integrations between the LAMP backend, and Unity3D game.
- Developed game play analytics used in real time for scaffolding, online dashboards, and data sets for researchers.
- Collaborated in acquisition of Phase I and Phase II National Science Foundation SBIR Grants.
- Collaborated with researchers at RIT for efficacy play testing.

=C#= =Unity3D= =PHP= =JavaScript= =MySql=

**** Oxford Music
:Properties:
:CV_ENV:   cvproject
:ROLE:     Lead Developer
:LINK: https://www.youtube.com/watch?v=YcBUUJt8nH8
:ICON: Youtube
:END:

Provides hundreds of dynamically generated exercises in an online environment where students can practice and master core concepts in Music Fundamentals. Starting with an incomplete platform, we assessed and completed the product for release.
- Added additional question types including ones with audio produced dynamically.
- Added, performance tuned, and removed bugs in question generating algorithms.
- Created LTI integration module allowing the application to be plugged into supporting LMS (including Moodle).

=AS3= =C\#= =VB= =ASP.NET= =PHP= =XSLT= =JS= =MSSQL=

**** K12 Virtual Labs
:Properties:
:CV_ENV:   cvproject
:ROLE:     Lead Developer
:End:
Contracted by k12 to create online virtual labs designed to look and feel like real hands-on labs.

- Designed and Developed 9 physical science and biology virtual labs.
- Collaborated with k12 and subject matter experts to produce manuscripts and storyboards.
- Labs tested well with teachers, and are featured on k12’s sample labs page.

=AS3=

**** Pierson Realtors
:Properties:
:CV_ENV:   cvproject
:ICON: Link
:LINK: https://www.piersonrealtors.com/
:ROLE:     Lead Developer
:End:

A website for Pierson Realtors in Rochester NY. Built with play framework 1, gwt, and JavaScript.
- Developed listing search and the nightly jobs pulling data from the MLS via RETS.
- Developed admin area for admins/realtors to customize content of site.

=Play Framework= =GWT= =Javascript=

**** Targets
:Properties:
:CV_ENV:   cvproject
:ICON: Youtube
:LINK: https://www.youtube.com/watch?v=mcRJXqjUazU
:ROLE:     Game Programmer
:End:
Android tablet based augmented reality card game that teaches chemistry. Students are given world filled with molecules, and are challenged to break compounds apart and reform them to make new compounds.
- Developed game engine with real-time molecule physics/comparisons of complex compounds like amino acids.

=Unity3D= =C\#=

**** CyGames
:Properties:
:CV_ENV:   cvproject
:ICON: Link
:LINK: http://selene.cet.edu/default.aspx?page=news&id=104
:ROLE:     Game Programmer
:End:
A serious game about lunar accretion, differentiation, impact cratering, and volcanism. Players construct their own moon and blast it with impact craters. Researching approaches to instructional game design and assessment.
- Programmed game play and graphics for the game.
- Developed analytics and XML configuration systems, so alternate games could be produced and analyzed.

=AS3= =PHP=


